# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dict_style.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dict_Window(object):
    def setupUi(self, dict_Window):
        dict_Window.setObjectName("dict_Window")
        dict_Window.resize(701, 386)
        self.dictMain = QtWidgets.QWidget(dict_Window)
        self.dictMain.setObjectName("dictMain")
        self.wordsList = QtWidgets.QListWidget(self.dictMain)
        self.wordsList.setGeometry(QtCore.QRect(10, 40, 241, 331))
        self.wordsList.setObjectName("wordsList")
        self.dictSourceChoose = QtWidgets.QComboBox(self.dictMain)
        self.dictSourceChoose.setGeometry(QtCore.QRect(100, 10, 121, 21))
        self.dictSourceChoose.setObjectName("dictSourceChoose")
        self.DictSourceLabel = QtWidgets.QLabel(self.dictMain)
        self.DictSourceLabel.setGeometry(QtCore.QRect(20, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DictSourceLabel.setFont(font)
        self.DictSourceLabel.setObjectName("DictSourceLabel")
        self.inputTextEdit = QtWidgets.QPlainTextEdit(self.dictMain)
        self.inputTextEdit.setGeometry(QtCore.QRect(260, 10, 431, 41))
        self.inputTextEdit.setObjectName("inputTextEdit")
        self.resultText = QtWidgets.QTextBrowser(self.dictMain)
        self.resultText.setGeometry(QtCore.QRect(260, 60, 431, 311))
        self.resultText.setObjectName("resultText")
        dict_Window.setCentralWidget(self.dictMain)

        self.retranslateUi(dict_Window)
        QtCore.QMetaObject.connectSlotsByName(dict_Window)

    def retranslateUi(self, dict_Window):
        _translate = QtCore.QCoreApplication.translate
        dict_Window.setWindowTitle(_translate("dict_Window", "WordSearch"))
        self.DictSourceLabel.setText(_translate("dict_Window", "词典来源:"))
