# Form implementation generated from reading ui file '.\getSecret_style.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_getSecretWidget(object):
    def setupUi(self, getSecretWidget):
        getSecretWidget.setObjectName("getSecretWidget")
        getSecretWidget.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        getSecretWidget.resize(338, 359)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(getSecretWidget.sizePolicy().hasHeightForWidth())
        getSecretWidget.setSizePolicy(sizePolicy)
        getSecretWidget.setMaximumSize(QtCore.QSize(338, 359))
        getSecretWidget.setMouseTracking(True)
        self.ListWidget_Secrets = QtWidgets.QListWidget(getSecretWidget)
        self.ListWidget_Secrets.setGeometry(QtCore.QRect(10, 60, 321, 251))
        self.ListWidget_Secrets.setObjectName("ListWidget_Secrets")
        self.Label_MasterTitle = QtWidgets.QLabel(getSecretWidget)
        self.Label_MasterTitle.setGeometry(QtCore.QRect(10, 10, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(21)
        self.Label_MasterTitle.setFont(font)
        self.Label_MasterTitle.setObjectName("Label_MasterTitle")
        self.PushButton_Confirm = QtWidgets.QPushButton(getSecretWidget)
        self.PushButton_Confirm.setEnabled(False)
        self.PushButton_Confirm.setGeometry(QtCore.QRect(230, 320, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PushButton_Confirm.setFont(font)
        self.PushButton_Confirm.setObjectName("PushButton_Confirm")
        self.PushButton_Get = QtWidgets.QPushButton(getSecretWidget)
        self.PushButton_Get.setGeometry(QtCore.QRect(110, 320, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PushButton_Get.setFont(font)
        self.PushButton_Get.setObjectName("PushButton_Get")

        self.retranslateUi(getSecretWidget)
        self.PushButton_Get.clicked.connect(getSecretWidget.fillListWithSecret) # type: ignore
        self.ListWidget_Secrets.doubleClicked['QModelIndex'].connect(getSecretWidget.checkSecret) # type: ignore
        self.ListWidget_Secrets.currentRowChanged['int'].connect(getSecretWidget.checkCurrectIsAvailable) # type: ignore
        self.PushButton_Confirm.clicked.connect(getSecretWidget.save) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(getSecretWidget)

    def retranslateUi(self, getSecretWidget):
        _translate = QtCore.QCoreApplication.translate
        getSecretWidget.setWindowTitle(_translate("getSecretWidget", "获取OCR密钥"))
        self.Label_MasterTitle.setText(_translate("getSecretWidget", "双击验证密钥可用性"))
        self.PushButton_Confirm.setText(_translate("getSecretWidget", "使用选中密钥"))
        self.PushButton_Get.setText(_translate("getSecretWidget", "获取密钥"))
