# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\OCR_style.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OCR_Window(object):
    def setupUi(self, OCR_Window):
        OCR_Window.setObjectName("OCR_Window")
        OCR_Window.setEnabled(True)
        OCR_Window.resize(800, 546)
        OCR_Window.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        OCR_Window.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(OCR_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.OCRResultTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.OCRResultTextEdit.setGeometry(QtCore.QRect(30, 60, 721, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(18)
        self.OCRResultTextEdit.setFont(font)
        self.OCRResultTextEdit.setObjectName("OCRResultTextEdit")
        self.TransResult_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.TransResult_1.setGeometry(QtCore.QRect(30, 160, 721, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(18)
        self.TransResult_1.setFont(font)
        self.TransResult_1.setObjectName("TransResult_1")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(30, 260, 721, 71))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.ChooseAreaButton = QtWidgets.QPushButton(self.centralwidget)
        self.ChooseAreaButton.setGeometry(QtCore.QRect(530, 12, 111, 31))
        self.ChooseAreaButton.setObjectName("ChooseAreaButton")
        self.ChosenTitleText = QtWidgets.QLabel(self.centralwidget)
        self.ChosenTitleText.setGeometry(QtCore.QRect(680, 10, 81, 20))
        self.ChosenTitleText.setAlignment(QtCore.Qt.AlignCenter)
        self.ChosenTitleText.setObjectName("ChosenTitleText")
        self.PosText = QtWidgets.QLabel(self.centralwidget)
        self.PosText.setGeometry(QtCore.QRect(650, 30, 141, 20))
        self.PosText.setAlignment(QtCore.Qt.AlignCenter)
        self.PosText.setObjectName("PosText")
        self.OCRButton = QtWidgets.QPushButton(self.centralwidget)
        self.OCRButton.setGeometry(QtCore.QRect(30, 10, 111, 31))
        self.OCRButton.setObjectName("OCRButton")
        OCR_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(OCR_Window)
        self.ChooseAreaButton.clicked.connect(OCR_Window.getScreenPos) # type: ignore
        self.OCRButton.clicked.connect(OCR_Window.getOCRText) # type: ignore
        OCR_Window.ocrHotkeyPressed.connect(OCR_Window.getOCRText) # type: ignore
        self.OCRResultTextEdit.textChanged.connect(OCR_Window.updateResult_1) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(OCR_Window)

    def retranslateUi(self, OCR_Window):
        _translate = QtCore.QCoreApplication.translate
        OCR_Window.setWindowTitle(_translate("OCR_Window", "MainWindow"))
        self.ChooseAreaButton.setText(_translate("OCR_Window", "选取区域"))
        self.ChosenTitleText.setText(_translate("OCR_Window", "已选择的区域"))
        self.PosText.setText(_translate("OCR_Window", "(0,0),(0,0)"))
        self.OCRButton.setText(_translate("OCR_Window", "OCR"))
